name: Publish VS Code Extension

on:
  push:
    tags:
      - 'v*'  

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Test Go
        run: go test ./gbnf-engine/tests

      - uses: actions/setup-node@v4
        with:
          node-version: 21
      - run: npm ci && npm run build
      - name: Publish to Open VSX Registry
        uses: HaaLeo/publish-vscode-extension@v2
        with:
          pat: ${{ secrets.OPEN_VSX_TOKEN }}
